# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 988f3b1ffc1378286086c6e1fd3fde58a3b25f475495388c59d59ee82307aa527777fe9f517a193307179129897ace1a54db18d72b9ad7cf36d9571048e172ae

test:
  secret_key_base: 0288f9867e06f785a4a51ab8f7c780a10f1751a5f495f66999ad32c2b8ebc256e508cf5899dbdf913a7075c9752bcfc52b071b261989eb54408f6ba33943528f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
